export const FOREMAN_DISPATCH_CHILD_ENV = "FOREMAN_DISPATCH_CHILD";
export const FOREMAN_DISPATCH_RUN_ID_ENV = "FOREMAN_DISPATCH_RUN_ID";
export const FOREMAN_DISPATCH_ATTEMPT_ID_ENV = "FOREMAN_DISPATCH_ATTEMPT_ID";
export const FOREMAN_DISPATCH_TASK_ID_ENV = "FOREMAN_DISPATCH_TASK_ID";
export const FOREMAN_DISPATCH_CHUNK_ID_ENV = "FOREMAN_DISPATCH_CHUNK_ID";
